# Generated by Django 2.2.7 on 2019-11-17 00:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontoturistico_avaliacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avalicao',
            new_name='Avaliacao',
        ),
    ]
